### ISSUE TITLE
Crash when other `noqa` comments are present

### ISSUE THREAD

**Issue by jamesbraza** [geo7/mypy_clean_slate#110]
There seems to be an edge case with Python 3.11.8, `mypy==1.9.0`, and `mypy_clean_slate==0.3.1`:

```python
class Foo:
    bar: dict = {  # noqa: RUF012
        "int": int,
    }

```

Running `mypy_clean_slate -ra`, I get a crash:

```none
Generating mypy report using: mypy . --show-error-codes --no-pretty --strict
Traceback (most recent call last):
  File "/Users/user/code/repo/venv/bin/mypy_clean_slate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/mypy_clean_slate/main.py", line 293, in main
    add_type_ignores(report_output=report_output)
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/mypy_clean_slate/main.py", line 214, in add_type_ignores
    update_files(file_updates=file_updates)
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/mypy_clean_slate/main.py", line 153, in update_files
    python_code, python_comment = extract_code_comment(line=file_lines[line_number])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/mypy_clean_slate/main.py", line 111, in extract_code_comment
    comment_tokens = [t for t in tokenize.generate_tokens(reader) if t.type == tokenize.COMMENT]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/mypy_clean_slate/main.py", line 111, in <listcomp>
    comment_tokens = [t for t in tokenize.generate_tokens(reader) if t.type == tokenize.COMMENT]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.8/lib/python3.11/tokenize.py", line 525, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (2, 0))
```

Here is the `mypy_error_report.txt`:

```txt
a.py: note: In class "Foo":
a.py:2:10: error: Missing type parameters for generic type "dict"  [type-arg]
```

**Comment by geo7** [comment]
Makes sense thanks - for now will raise a warning, have created https://github.com/geo7/mypy_clean_slate/issues/114 to handle it properly though as it shouldn't fail out.
